### PR TITLE
Adding composer.json, composer.lock and vendor/ + change of namespace App\ to Att\ to avoid confusion

### PR DESCRIPTION
**Pull request by Kinany52**
@gulasz101 after over a dozen of failed attempts with the command `docker run -it --rm -v ${PWD}:/app composer init` in Git Bash, Hyper Terminal and CMD, there was still no **composer.json** file in my parent working directory. After consulting you about the issue (via WhatsApp on 19.12.2021) you suggested that I use Window's built-in PowerShell. Thanks to you, the **composer.json** file and **vendor/** dir were successfully created with PowerShell, but there was no `composer.lock` file. For that, I ran the command `composer install` and finally `composer.lock` file was created.

I previously had a directory in src/ with the name **App**, I changed its name to **Att** and thus renamed all files that contained the namespace and keyword **App\\** and changed it to **Att\\** to avoid confusion. That is why you might notice a change in 8 different php files.

### CODE REVIEW

**Comment by Kinany52** [comment]
4Cap

The previous pull request is not yet approved by @gulasz101 (steps 1, 2 & 3 in the attached .JPG file).
Step 4 [pull out dir config from dir src and put it next to dir src] cannot be created as a new pull request since the previous PR has yet not been approved by @gulasz101, but the changes (of step 4) are already made to the Master branch (but not merged yet).

**Comment by gulasz101** [comment]
In general good work, now few remarks:
- ~~vendor directory usually is not included under version control, how usually it works, every dev who works on your project has to run composer instal by himself so this way repo is slimmer, to keep everyone with the same version of dependencies, you just need to add composer.json and composer.lock to repo as you did correctly, to kill vendor from you git repo just get familiar with: https://git-scm.com/docs/git-rm~~

- I see you are using a lot of include('something/config') in your code, if you need to have access your config everywhere, just use autoload/file in you composer.json, under psr-4 section, you are introducing files section and giving list of files you want to be available globally in your project, in general it is bad practice, but we will cover it in future, as a starting point please take a look on: https://getcomposer.org/doc/04-schema.md#files

- ~~another thing, correct me if i'm wrong, in your `index.php` which I believe should be starting point of your app, you should use something like ``` require(__DIR__ . "/../vendor/autoload.php");``` this way your app will be familiar with whole autoload logic from composer~~

- ~~last thing: in you `composer.json` you have specified your root namespace with name `Root\\App\\` but everywhere in code you are using stuff like `Att\DropShipper\User` how this is even working? As far I'm aware, composer 2 isnot able to autoload such thing.~~

If any questions, please slack me.

**Comment by Kinany52** [comment]
wlsCapture

in master branch: git branch -d main (Local branch main deleted.)
in master branch: git checkout -b main origin/main (Switched to new branch 'main'. New branch 'main' set up to track remote branch 'main' from 'origin'.)

**Comment by gulasz101** [comment]
As follow up to previous comment, I will still upload the image here, as I can see namespaces are still not fixed:

image

**Comment by gulasz101** [comment]
Small follow up config.php from my previous comment.

Below you have visual explanation how we can autoload config with composer the clean way. This is not 100% yet super clean, but for current state of project it is more than enough. 
VRM_config_helper_autoload

**Comment by Kinany52** [comment]
> As follow up to previous comment, I will still upload the image here, as I can see namespaces are still not fixed:
> 
> image

**Comment by Kinany52** [comment]
New commit: Namespaces fixed 102 (& 2 functions added)
CJCapture
NSCapture

**Comment by Kinany52** [comment]
Minor changes committed & pushed: **require()/include() clean-ups**

**Pull request merged**
